/**
 * Tool metadata + inputs for the skilled-trades calculator pack.
 * Formulas live in src/lib/formulas_trades.ts.
 */

import {
  CONSTRUCTION_TRADES_CATEGORY,
  ELECTRICAL_TRADES_CATEGORY,
  HVAC_TRADES_CATEGORY,
  LANDSCAPING_TRADES_CATEGORY,
  MASONRY_TRADES_CATEGORY,
  PLUMBING_TRADES_CATEGORY,
  ROOFING_TRADES_CATEGORY,
} from "@/lib/categoryPaths";

export type TradesInputSpec = [
  string,
  string,
  number,
  number,
  number,
  number,
];

export type TradesPackToolSpec = {
  slug: string;
  title: string;
  category: string;
  seoH1: string;
  seoDescription: string;
  focusKeyword: string;
  formulaType: string;
  description: string;
  formulaSummary: string;
  realWorldExample: string;
  inputs: TradesInputSpec[];
};

export const TRADES_PACK_SPECS: TradesPackToolSpec[] = [
  // ——— HVAC & Climate Control (9) ———
  {
    slug: "hvac-seer-savings-calculator",
    title: "HVAC SEER Savings Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "HVAC SEER Upgrade Savings Calculator — Annual Cost & Payback",
    seoDescription:
      "Compare old vs new SEER ratings to estimate annual cooling savings, kWh reduction, and payback on an HVAC upgrade.",
    focusKeyword: "hvac seer savings calculator",
    formulaType: "tradeHvacSeerSavings",
    description:
      "Estimate annual electricity savings when upgrading from an older SEER-rated AC to a higher-efficiency unit.",
    formulaSummary:
      "New kWh = old annual kWh × (old SEER ÷ new SEER); savings = kWh saved × $/kWh.",
    realWorldExample:
      "10 SEER → 16 SEER on 6,000 kWh/yr at $0.14/kWh saves ~2,250 kWh and ~$315/year.",
    inputs: [
      ["oldSeer", "Old system SEER", 10, 6, 20, 0.5],
      ["newSeer", "New system SEER", 16, 13, 30, 0.5],
      ["annualCoolingKwh", "Annual cooling kWh (old system)", 6000, 500, 30000, 100],
      ["kwhRate", "Electricity rate ($/kWh)", 0.14, 0.05, 0.5, 0.01],
      ["upgradeCost", "Upgrade cost ($)", 8000, 0, 50000, 100],
    ],
  },
  {
    slug: "hvac-btu-tonnage-calculator",
    title: "HVAC BTU Tonnage Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "AC Tonnage Calculator by Square Footage & Climate",
    seoDescription:
      "Size cooling load from square footage, climate zone factor, and insulation level to estimate required tons.",
    focusKeyword: "ac tonnage calculator by square feet",
    formulaType: "tradeHvacBtuTonnage",
    description: "Estimate AC tonnage from conditioned square footage and building factors.",
    formulaSummary: "Tons ≈ (sq ft ÷ 500) × climate × insulation factors; BTU = tons × 12,000.",
    realWorldExample: "1,800 sq ft, warm climate (1.15), average insulation → ~4.1 tons.",
    inputs: [
      ["sqFt", "Conditioned sq ft", 1800, 400, 10000, 50],
      ["climateFactor", "Climate factor (1.0–1.3)", 1.1, 0.9, 1.3, 0.05],
      ["insulationFactor", "Insulation factor (0.8–1.2)", 1, 0.8, 1.2, 0.05],
    ],
  },
  {
    slug: "ductwork-cfm-calculator",
    title: "Ductwork CFM Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "HVAC Duct CFM Calculator — Airflow from Duct Size",
    seoDescription: "Calculate duct airflow CFM from round duct diameter and air velocity.",
    focusKeyword: "ductwork cfm calculator",
    formulaType: "tradeDuctworkCfm",
    description: "Compute CFM through round duct from diameter and velocity.",
    formulaSummary: "CFM = duct area (sq ft) × velocity (ft/min).",
    realWorldExample: "8 in round duct at 900 FPM → ~314 CFM.",
    inputs: [
      ["ductDiameterIn", "Duct diameter (in)", 8, 4, 24, 0.5],
      ["velocityFpm", "Air velocity (FPM)", 900, 400, 2000, 50],
    ],
  },
  {
    slug: "heat-pump-cop-savings-calculator",
    title: "Heat Pump COP Savings Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "Heat Pump vs Furnace Savings Calculator",
    seoDescription:
      "Compare heat pump COP to furnace AFUE for annual heating cost and savings.",
    focusKeyword: "heat pump cop savings calculator",
    formulaType: "tradeHeatPumpCopSavings",
    description: "Compare annual heating cost between a furnace and a heat pump.",
    formulaSummary:
      "Furnace kWh equiv = therms × 29.3; heat pump kWh = heat BTU ÷ (COP × 3,412).",
    realWorldExample:
      "600 therms at AFUE 80% vs COP 3.2 heat pump at $0.14/kWh → meaningful winter savings.",
    inputs: [
      ["annualTherms", "Annual heating therms", 600, 50, 3000, 10],
      ["furnaceAfue", "Furnace AFUE (%)", 80, 60, 98, 1],
      ["heatPumpCop", "Heat pump COP", 3.2, 2, 5, 0.1],
      ["electricRate", "Electric rate ($/kWh)", 0.14, 0.05, 0.5, 0.01],
      ["gasRate", "Gas rate ($/therm)", 1.5, 0.5, 5, 0.05],
    ],
  },
  {
    slug: "hvac-service-call-price-calculator",
    title: "HVAC Service Call Price Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "HVAC Service Call Pricing Calculator",
    seoDescription:
      "Price an HVAC diagnostic or service call with labor, travel, parts, and margin.",
    focusKeyword: "hvac service call price calculator",
    formulaType: "tradeHvacServiceCallPrice",
    description: "Build a profitable HVAC service call quote.",
    formulaSummary: "Cost = labor + travel + parts; price = cost ÷ (1 − margin%).",
    realWorldExample: "1.5 hrs × $85 + $25 travel + $40 parts, 25% margin → ~$198 call price.",
    inputs: [
      ["hours", "Labor hours", 1.5, 0.25, 8, 0.25],
      ["hourlyRate", "Labor rate ($/hr)", 85, 40, 200, 5],
      ["travel", "Travel / trip charge ($)", 25, 0, 150, 5],
      ["parts", "Parts ($)", 40, 0, 500, 5],
      ["marginPercent", "Target margin (%)", 25, 0, 60, 1],
    ],
  },
  {
    slug: "mini-split-head-count-calculator",
    title: "Mini Split Head Count Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "How Many Mini Split Heads Do I Need? Calculator",
    seoDescription:
      "Estimate mini-split head count from total BTU load and per-head capacity.",
    focusKeyword: "how many mini split heads do i need calculator",
    formulaType: "tradeMiniSplitHeadCount",
    description: "Size mini-split systems by dividing total load across head capacities.",
    formulaSummary: "Heads needed = ceil(total BTU load ÷ BTU per head).",
    realWorldExample: "36,000 BTU load with 12,000 BTU heads → 3 heads.",
    inputs: [
      ["totalBtuLoad", "Total BTU load", 36000, 6000, 120000, 1000],
      ["headCapacityBtu", "BTU per head", 12000, 9000, 36000, 1000],
    ],
  },
  {
    slug: "furnace-afue-savings-calculator",
    title: "Furnace AFUE Savings Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "Furnace AFUE Upgrade Savings Calculator",
    seoDescription:
      "Compare old vs new furnace AFUE for annual gas savings and upgrade payback.",
    focusKeyword: "furnace afue savings calculator",
    formulaType: "tradeFurnaceAfueSavings",
    description: "Estimate gas savings when upgrading furnace efficiency (AFUE).",
    formulaSummary:
      "Useful heat fixed; new therms = old therms × (old AFUE ÷ new AFUE).",
    realWorldExample: "600 therms at 80% AFUE → 95% AFUE saves ~95 therms/year.",
    inputs: [
      ["oldAfue", "Old AFUE (%)", 80, 60, 95, 1],
      ["newAfue", "New AFUE (%)", 95, 80, 98, 1],
      ["annualTherms", "Annual gas therms", 600, 50, 3000, 10],
      ["gasRate", "Gas rate ($/therm)", 1.5, 0.5, 5, 0.05],
      ["upgradeCost", "Upgrade cost ($)", 4500, 0, 25000, 100],
    ],
  },
  {
    slug: "refrigerant-charge-estimator",
    title: "Refrigerant Charge Estimator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "AC Line Set Refrigerant Charge Calculator",
    seoDescription:
      "Estimate refrigerant charge in ounces from line set length and diameter.",
    focusKeyword: "r410a charge calculator line set",
    formulaType: "tradeRefrigerantCharge",
    description: "Estimate additional refrigerant for line set length beyond factory charge.",
    formulaSummary: "Charge oz ≈ length × oz per foot (by line diameter).",
    realWorldExample: "25 ft of 3/8 in line set → ~6–8 oz additional R-410A.",
    inputs: [
      ["lineLengthFt", "Line set length (ft)", 25, 5, 100, 1],
      ["lineDiameterIn", "Line diameter (in)", 0.375, 0.25, 0.75, 0.0625],
      ["ozPerFoot", "Oz per foot (refrigerant)", 0.3, 0.1, 1, 0.05],
    ],
  },
  {
    slug: "hvac-install-quote-calculator",
    title: "HVAC Install Quote Calculator",
    category: HVAC_TRADES_CATEGORY,
    seoH1: "HVAC Installation Cost Calculator",
    seoDescription:
      "Build an HVAC install quote from equipment, labor, permits, and markup.",
    focusKeyword: "hvac installation cost calculator",
    formulaType: "tradeHvacInstallQuote",
    description: "Estimate installed HVAC price with labor and permit add-ons.",
    formulaSummary: "Install price = (equipment + labor + permits) × (1 + markup%).",
    realWorldExample: "$4,200 equipment + 8 hrs × $75 + $150 permit, 15% markup → ~$5,175.",
    inputs: [
      ["equipmentCost", "Equipment ($)", 4200, 500, 50000, 100],
      ["laborHours", "Labor hours", 8, 2, 40, 0.5],
      ["laborRate", "Labor rate ($/hr)", 75, 40, 200, 5],
      ["permits", "Permits / fees ($)", 150, 0, 2000, 25],
      ["markupPercent", "Markup (%)", 15, 0, 50, 1],
    ],
  },

  // ——— Plumbing & Piping (11) ———
  {
    slug: "water-heater-sizing-calculator",
    title: "Water Heater Sizing Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Water Heater Tank Size Calculator — Gallons by Household",
    seoDescription:
      "Recommend tank water heater size from household occupants, peak demand, and temperature rise.",
    focusKeyword: "water heater sizing calculator",
    formulaType: "tradeWaterHeaterSizing",
    description:
      "Estimate recommended tank water heater capacity from household size and peak hot-water demand.",
    formulaSummary:
      "Base gallons by occupants (40/50/75 gal tiers) plus peak-demand adjustment.",
    realWorldExample: "4 occupants, 30-min peak, 60 °F rise → 50 gal tank recommended.",
    inputs: [
      ["occupants", "Household occupants", 4, 1, 10, 1],
      ["peakDemandMinutes", "Peak demand window (min)", 30, 10, 60, 5],
      ["tempRiseF", "Temperature rise (°F)", 60, 40, 90, 5],
    ],
  },
  {
    slug: "pipe-length-fittings-calculator",
    title: "Pipe Length & Fittings Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Pipe Run Length Calculator with Fittings Allowance",
    seoDescription: "Estimate total pipe length including fittings allowance for a plumbing run.",
    focusKeyword: "pipe length fittings calculator",
    formulaType: "tradePipeLengthFittings",
    description: "Total pipe = straight run + fittings allowance per joint.",
    formulaSummary: "Total length = straight run + (fittings × allowance per fitting).",
    realWorldExample: "40 ft straight + 12 fittings × 1.5 ft allowance → 58 ft pipe ordered.",
    inputs: [
      ["straightRunFt", "Straight run (ft)", 40, 5, 500, 1],
      ["fittingsCount", "Fittings count", 12, 0, 200, 1],
      ["allowancePerFittingFt", "Allowance per fitting (ft)", 1.5, 0.5, 3, 0.25],
    ],
  },
  {
    slug: "drain-slope-calculator",
    title: "Drain Slope Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Drain Pipe Slope Calculator — Fall per Foot",
    seoDescription: "Calculate drain slope % and total fall from run length and drop.",
    focusKeyword: "drain slope calculator",
    formulaType: "tradeDrainSlope",
    description: "Compute drain grade from horizontal run and vertical drop.",
    formulaSummary: "Slope % = (drop ÷ run) × 100; fall per foot = drop ÷ run.",
    realWorldExample: "20 ft run with 5 in drop → 2.08% slope, 0.25 in/ft fall.",
    inputs: [
      ["runLengthFt", "Horizontal run (ft)", 20, 1, 200, 1],
      ["dropIn", "Vertical drop (in)", 5, 0.5, 24, 0.25],
    ],
  },
  {
    slug: "fixture-unit-load-calculator",
    title: "Fixture Unit Load Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Plumbing Fixture Unit Calculator for DWV Sizing",
    seoDescription: "Sum fixture units from toilets, lavs, and appliances for DWV branch sizing.",
    focusKeyword: "fixture unit load calculator",
    formulaType: "tradeFixtureUnitLoad",
    description: "Estimate total DWV fixture units for drain sizing.",
    formulaSummary: "Total FU = toilets×4 + lavs×1 + tubs×2 + kitchen×2 (typical IPC values).",
    realWorldExample: "2 toilets + 3 lavs + 1 tub + 1 kitchen → 15 fixture units.",
    inputs: [
      ["toilets", "Toilets", 2, 0, 10, 1],
      ["lavs", "Lavatories", 3, 0, 10, 1],
      ["tubs", "Tubs / showers", 1, 0, 5, 1],
      ["kitchen", "Kitchen sinks", 1, 0, 3, 1],
    ],
  },
  {
    slug: "plumbing-job-bid-calculator",
    title: "Plumbing Job Bid Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Plumbing Job Quote Calculator — Labor & Materials",
    seoDescription: "Quote plumbing jobs from materials, labor, overhead, and margin.",
    focusKeyword: "plumbing job bid calculator",
    formulaType: "tradePlumbingJobBid",
    description: "Build a plumbing job bid with margin on direct costs.",
    formulaSummary: "Price = (materials + labor + overhead) ÷ (1 − margin%).",
    realWorldExample: "$800 materials + 6 hrs × $70 + $100 overhead, 30% margin → ~$1,457.",
    inputs: [
      ["materials", "Materials ($)", 800, 0, 50000, 25],
      ["laborHours", "Labor hours", 6, 0, 200, 0.5],
      ["laborRate", "Labor rate ($/hr)", 70, 30, 200, 5],
      ["overhead", "Overhead ($)", 100, 0, 5000, 25],
      ["marginPercent", "Target margin (%)", 30, 0, 60, 1],
    ],
  },
  {
    slug: "tankless-water-heater-gpm-calculator",
    title: "Tankless Water Heater GPM Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Tankless Water Heater Size Calculator — GPM by Fixtures",
    seoDescription:
      "Size tankless water heater GPM from fixture flow rates and temperature rise.",
    focusKeyword: "tankless water heater size calculator gpm",
    formulaType: "tradeTanklessWaterHeaterGpm",
    description: "Sum fixture GPM demands for peak simultaneous hot water use.",
    formulaSummary: "Required GPM = sum of simultaneous fixture flow rates.",
    realWorldExample: "Shower 2.5 + kitchen 1.5 + lav 0.5 GPM → 4.5 GPM unit needed.",
    inputs: [
      ["showerGpm", "Shower GPM", 2.5, 1, 5, 0.1],
      ["kitchenGpm", "Kitchen / appliance GPM", 1.5, 0, 4, 0.1],
      ["otherGpm", "Other fixtures GPM", 1, 0, 5, 0.1],
      ["tempRiseF", "Temperature rise (°F)", 60, 40, 90, 5],
    ],
  },
  {
    slug: "sump-pump-sizing-calculator",
    title: "Sump Pump Sizing Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Sump Pump Sizing Calculator — GPH by Basement Area",
    seoDescription: "Estimate sump pump GPH from basement square footage and head height.",
    focusKeyword: "sump pump sizing calculator",
    formulaType: "tradeSumpPumpSizing",
    description: "Size sump pump capacity from catchment area and lift head.",
    formulaSummary: "GPH ≈ basement sq ft × in/hr rainfall factor × head adjustment.",
    realWorldExample: "800 sq ft basement, 1 in/hr, 8 ft head → ~2,400+ GPH pump class.",
    inputs: [
      ["basementSqFt", "Basement sq ft", 800, 200, 5000, 50],
      ["rainfallInPerHr", "Design rainfall (in/hr)", 1, 0.25, 3, 0.25],
      ["headHeightFt", "Head height (ft)", 8, 3, 20, 1],
    ],
  },
  {
    slug: "septic-tank-size-calculator",
    title: "Septic Tank Size Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Septic Tank Size Calculator by Bedrooms",
    seoDescription: "Estimate septic tank gallons from bedrooms and daily flow per person.",
    focusKeyword: "septic tank size calculator",
    formulaType: "tradeSepticTankSize",
    description: "Size septic tank from bedroom count and daily wastewater flow.",
    formulaSummary: "Tank gal = bedrooms-based minimum + flow buffer (local code varies).",
    realWorldExample: "4 bedrooms, 75 gal/person/day → 1,000–1,250 gal tank typical.",
    inputs: [
      ["bedrooms", "Bedrooms", 4, 1, 8, 1],
      ["gallonsPerPerson", "Gallons per person/day", 75, 50, 100, 5],
      ["occupants", "Occupants", 5, 1, 12, 1],
    ],
  },
  {
    slug: "pex-vs-copper-cost-calculator",
    title: "PEX vs Copper Cost Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "PEX vs Copper Pipe Cost Compare Calculator",
    seoDescription: "Compare PEX vs copper material cost for a plumbing run including fittings.",
    focusKeyword: "pex vs copper cost calculator",
    formulaType: "tradePexVsCopperCost",
    description: "Side-by-side material cost for PEX vs copper by linear foot.",
    formulaSummary: "Cost = linear ft × $/ft + fittings allowance for each material.",
    realWorldExample: "60 ft run: PEX $1.2/ft vs copper $3.5/ft → ~$72 vs ~$210 materials.",
    inputs: [
      ["linearFt", "Linear feet", 60, 5, 500, 1],
      ["pexCostPerFt", "PEX ($/ft)", 1.2, 0.5, 5, 0.1],
      ["copperCostPerFt", "Copper ($/ft)", 3.5, 1, 10, 0.1],
      ["fittingsCost", "Fittings allowance ($)", 45, 0, 500, 5],
    ],
  },
  {
    slug: "water-pressure-loss-calculator",
    title: "Water Pressure Loss Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Pipe Pressure Drop Calculator",
    seoDescription: "Estimate PSI loss through pipe from diameter, length, and flow GPM.",
    focusKeyword: "pipe pressure drop calculator",
    formulaType: "tradeWaterPressureLoss",
    description: "Approximate friction pressure loss in water pipe runs.",
    formulaSummary: "PSI loss scales with length and flow, inversely with diameter².",
    realWorldExample: "50 ft of 3/4 in pipe at 5 GPM → modest PSI drop; 1/2 in shows more loss.",
    inputs: [
      ["pipeDiameterIn", "Pipe diameter (in)", 0.75, 0.5, 2, 0.125],
      ["lengthFt", "Pipe length (ft)", 50, 5, 500, 5],
      ["flowGpm", "Flow (GPM)", 5, 1, 20, 0.5],
    ],
  },
  {
    slug: "bathroom-rough-in-cost-calculator",
    title: "Bathroom Rough-In Cost Calculator",
    category: PLUMBING_TRADES_CATEGORY,
    seoH1: "Bathroom Plumbing Rough-In Cost Estimator",
    seoDescription:
      "Estimate bathroom rough-in plumbing cost from fixture count and labor rate.",
    focusKeyword: "bathroom plumbing rough in cost calculator",
    formulaType: "tradeBathroomRoughInCost",
    description: "Ballpark rough-in cost from fixtures and labor hours per fixture.",
    formulaSummary: "Cost = fixtures × hours/fixture × labor rate + materials allowance.",
    realWorldExample: "4 fixtures × 3 hrs × $70/hr + $200 materials → ~$1,040 rough-in.",
    inputs: [
      ["fixtures", "Fixture count", 4, 1, 10, 1],
      ["hoursPerFixture", "Hours per fixture", 3, 1, 8, 0.5],
      ["laborRate", "Labor rate ($/hr)", 70, 40, 200, 5],
      ["materialsAllowance", "Materials ($)", 200, 0, 2000, 25],
    ],
  },

  // ——— Electrical & Wiring (11) ———
  {
    slug: "wire-gauge-ampacity-calculator",
    title: "Wire Gauge Ampacity Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Wire Gauge Ampacity Calculator — Size Wire by Load & Length",
    seoDescription:
      "Suggest copper wire gauge from load amps, circuit length, and voltage with voltage-drop check.",
    focusKeyword: "wire gauge ampacity calculator",
    formulaType: "tradeWireGaugeAmpacity",
    description:
      "Suggest wire gauge for a circuit load and check voltage drop against the 3% guideline.",
    formulaSummary:
      "Match load amps to NEC-style ampacity table; estimate voltage drop over circuit length.",
    realWorldExample: "30 A load, 80 ft run at 240 V → 10 AWG suggested; ~2.1% voltage drop.",
    inputs: [
      ["loadAmps", "Load (amps)", 30, 1, 200, 1],
      ["circuitLengthFt", "Circuit length (ft, one way)", 80, 5, 500, 5],
      ["voltage", "Voltage (V)", 240, 110, 480, 10],
    ],
  },
  {
    slug: "voltage-drop-calculator",
    title: "Voltage Drop Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Electrical Voltage Drop Calculator",
    seoDescription: "Calculate voltage drop across wire length, load amps, and gauge.",
    focusKeyword: "voltage drop calculator",
    formulaType: "tradeVoltageDrop",
    description: "Compute voltage drop and percent loss for a circuit run.",
    formulaSummary: "V_drop = 2 × I × R × length; % = V_drop ÷ system voltage.",
    realWorldExample: "40 A on 100 ft with 8 AWG at 240 V → check if under 3% guideline.",
    inputs: [
      ["loadAmps", "Load (amps)", 40, 1, 200, 1],
      ["lengthFt", "One-way length (ft)", 100, 5, 500, 5],
      ["voltage", "System voltage (V)", 240, 110, 480, 10],
      ["wireGaugeAwG", "Wire gauge (AWG number: 14=14, 12=12…)", 8, 14, 2, 1],
    ],
  },
  {
    slug: "conduit-fill-calculator",
    title: "Conduit Fill Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Electrical Conduit Fill Calculator",
    seoDescription: "Check max conductors in conduit from conduit and wire diameters.",
    focusKeyword: "conduit fill calculator",
    formulaType: "tradeConduitFill",
    description: "Estimate conduit fill percent and max wire count at 40% fill.",
    formulaSummary: "Fill % = (wire area × count) ÷ conduit area; NEC 40% fill for 3+ wires.",
    realWorldExample: "1/2 in EMT with 12 AWG THHN — typically 9 wires max at 40% fill.",
    inputs: [
      ["conduitDiameterIn", "Conduit inner diameter (in)", 0.622, 0.3, 2, 0.01],
      ["wireDiameterIn", "Wire outer diameter (in)", 0.13, 0.05, 0.5, 0.01],
      ["wireCount", "Wire count", 6, 1, 20, 1],
    ],
  },
  {
    slug: "ev-charger-circuit-calculator",
    title: "EV Charger Circuit Sizing Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Level 2 EV Charger Circuit Sizing Calculator",
    seoDescription: "Size wire and breaker for Level 2 EV charger amps and run length.",
    focusKeyword: "ev charger circuit sizing calculator",
    formulaType: "tradeEvChargerCircuit",
    description: "Recommend breaker and wire for EV charger circuit with voltage drop check.",
    formulaSummary: "Breaker = 125% of continuous charger amps; wire sized for load + length.",
    realWorldExample: "40 A charger → 50 A breaker, 6 AWG typical for short 240 V runs.",
    inputs: [
      ["chargerAmps", "Charger amps (continuous)", 40, 16, 80, 1],
      ["lengthFt", "Run length (ft, one way)", 40, 5, 200, 5],
      ["voltage", "Voltage (V)", 240, 208, 240, 1],
    ],
  },
  {
    slug: "electrical-job-bid-calculator",
    title: "Electrical Job Bid Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Electrical Job Quote Calculator",
    seoDescription: "Quote electrical work from materials, labor, overhead, and margin.",
    focusKeyword: "electrical job bid calculator",
    formulaType: "tradeElectricalJobBid",
    description: "Build electrical job price with margin on direct costs.",
    formulaSummary: "Price = (materials + labor + overhead) ÷ (1 − margin%).",
    realWorldExample: "$1,200 materials + 10 hrs × $80 + $150 overhead, 25% margin → ~$2,187.",
    inputs: [
      ["materials", "Materials ($)", 1200, 0, 100000, 50],
      ["laborHours", "Labor hours", 10, 0, 500, 0.5],
      ["laborRate", "Labor rate ($/hr)", 80, 40, 250, 5],
      ["overhead", "Overhead ($)", 150, 0, 10000, 25],
      ["marginPercent", "Target margin (%)", 25, 0, 60, 1],
    ],
  },
  {
    slug: "generator-sizing-calculator",
    title: "Generator Sizing Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Whole House Generator Size Calculator",
    seoDescription:
      "Size standby generator kW from running watts and motor starting surge.",
    focusKeyword: "whole house generator size calculator",
    formulaType: "tradeGeneratorSizing",
    description: "Estimate generator kW from essential load and starting surge.",
    formulaSummary: "Generator kW ≈ (running watts + surge allowance) ÷ 1,000.",
    realWorldExample: "8,000 W running + 4,000 W surge → ~12 kW generator class.",
    inputs: [
      ["runningWatts", "Running watts", 8000, 1000, 50000, 500],
      ["surgeWatts", "Starting surge watts", 4000, 0, 30000, 500],
    ],
  },
  {
    slug: "solar-panel-array-calculator",
    title: "Solar Panel Array Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "How Many Solar Panels Do I Need? Calculator",
    seoDescription:
      "Size solar array from monthly kWh, sun hours, panel watts, and estimate payback.",
    focusKeyword: "how many solar panels do i need calculator",
    formulaType: "tradeSolarPanelArray",
    description: "Estimate panel count and payback from usage and production assumptions.",
    formulaSummary:
      "Panels = monthly kWh ÷ (panel W × sun hrs × 30 ÷ 1,000); payback = cost ÷ annual savings.",
    realWorldExample: "900 kWh/mo, 400 W panels, 5 sun hrs → ~15 panels; payback depends on rate.",
    inputs: [
      ["monthlyKwh", "Monthly kWh usage", 900, 100, 5000, 50],
      ["panelWatts", "Panel watts", 400, 300, 600, 10],
      ["sunHoursPerDay", "Peak sun hours/day", 5, 2, 8, 0.25],
      ["systemCost", "System cost ($)", 18000, 5000, 100000, 500],
      ["kwhRate", "Utility rate ($/kWh)", 0.14, 0.05, 0.5, 0.01],
    ],
  },
  {
    slug: "led-retrofit-payback-calculator",
    title: "LED Retrofit Payback Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "LED Retrofit Payback Calculator",
    seoDescription:
      "Compare old vs LED wattage for annual savings and payback months on retrofit cost.",
    focusKeyword: "led retrofit payback calculator",
    formulaType: "tradeLedRetrofitPayback",
    description: "Calculate LED retrofit savings and payback period.",
    formulaSummary: "Savings = (old W − LED W) × hours × rate; payback = retrofit cost ÷ annual savings.",
    realWorldExample: "32 W → 9 W × 12 hrs/day × 365 at $0.14/kWh saves ~$20/yr per bulb.",
    inputs: [
      ["oldWatts", "Old fixture watts", 32, 5, 200, 1],
      ["ledWatts", "LED watts", 9, 3, 50, 1],
      ["hoursPerDay", "Hours per day", 12, 1, 24, 1],
      ["retrofitCost", "Retrofit cost per fixture ($)", 25, 5, 200, 1],
      ["kwhRate", "Electric rate ($/kWh)", 0.14, 0.05, 0.5, 0.01],
      ["fixtureCount", "Fixture count", 20, 1, 500, 1],
    ],
  },
  {
    slug: "subpanel-load-calculator",
    title: "Subpanel Load Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Electrical Subpanel Load Calculator",
    seoDescription: "Sum circuit loads with spare capacity to recommend subpanel amperage.",
    focusKeyword: "subpanel load calculator",
    formulaType: "tradeSubpanelLoad",
    description: "Total load with spare percent → recommended subpanel size.",
    formulaSummary: "Required amps = sum of circuit loads × (1 + spare%).",
    realWorldExample: "60 A connected load + 25% spare → 75 A subpanel minimum.",
    inputs: [
      ["connectedLoadAmps", "Connected load (amps)", 60, 10, 400, 5],
      ["sparePercent", "Spare capacity (%)", 25, 0, 50, 5],
    ],
  },
  {
    slug: "commercial-lighting-load-calculator",
    title: "Commercial Lighting Load Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Commercial Lighting Load Calculator",
    seoDescription:
      "Calculate lighting kWh and breaker load from fixtures, watts, and hours.",
    focusKeyword: "commercial lighting load calculator",
    formulaType: "tradeCommercialLightingLoad",
    description: "Estimate monthly kWh and connected amps for commercial lighting.",
    formulaSummary: "kWh = fixtures × watts × hours/day × days; amps = total W ÷ voltage.",
    realWorldExample: "40 fixtures × 32 W × 10 hrs × 30 days → ~384 kWh/month.",
    inputs: [
      ["fixtures", "Fixture count", 40, 1, 1000, 1],
      ["wattsPerFixture", "Watts per fixture", 32, 5, 200, 1],
      ["hoursPerDay", "Hours per day", 10, 1, 24, 1],
      ["daysPerMonth", "Days per month", 30, 20, 31, 1],
      ["voltage", "Voltage (V)", 120, 110, 277, 1],
    ],
  },
  {
    slug: "baseboard-heater-sizing-calculator",
    title: "Baseboard Heater Sizing Calculator",
    category: ELECTRICAL_TRADES_CATEGORY,
    seoH1: "Electric Baseboard Heater Sizing Calculator",
    seoDescription:
      "Size baseboard heat from room square footage and heat loss factor.",
    focusKeyword: "baseboard heater sizing calculator",
    formulaType: "tradeBaseboardHeatSizing",
    description: "Estimate linear feet of baseboard from room size and heat loss.",
    formulaSummary: "BTU need = sq ft × heat loss factor; linear ft ≈ BTU ÷ watts/ft.",
    realWorldExample: "200 sq ft room at 10 BTU/sq ft → 2,000 BTU ≈ ~6 ft of standard baseboard.",
    inputs: [
      ["roomSqFt", "Room sq ft", 200, 50, 2000, 10],
      ["heatLossBtuPerSqFt", "Heat loss (BTU/sq ft)", 10, 5, 25, 1],
      ["wattsPerLinearFt", "Baseboard watts/linear ft", 250, 150, 400, 10],
    ],
  },

  // ——— Roofing & Exterior (10) ———
  {
    slug: "roofing-squares-calculator",
    title: "Roofing Squares Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Roofing Squares Calculator — Materials, Labor & Waste",
    seoDescription:
      "Calculate roofing squares from roof area, pitch factor, waste %, and per-square material and labor costs.",
    focusKeyword: "roofing squares calculator",
    formulaType: "tradeRoofingSquares",
    description:
      "Convert roof area to squares with pitch and waste, then estimate material and labor totals.",
    formulaSummary:
      "Squares = area × pitch factor × (1 + waste%) ÷ 100; cost = squares × $/square.",
    realWorldExample:
      "2,000 sq ft roof, 1.15 pitch, 10% waste, $120/sq materials + $80/sq labor → ~25.3 squares, ~$5,060.",
    inputs: [
      ["roofAreaSqFt", "Roof area (sq ft)", 2000, 200, 20000, 50],
      ["pitchFactor", "Pitch factor (e.g. 1.15 for 6/12)", 1.15, 1, 1.5, 0.01],
      ["wastePercent", "Waste (%)", 10, 5, 20, 1],
      ["materialPerSquare", "Materials ($/square)", 120, 50, 500, 5],
      ["laborPerSquare", "Labor ($/square)", 80, 30, 400, 5],
    ],
  },
  {
    slug: "shingle-bundle-count-calculator",
    title: "Shingle Bundle Count Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Roof Shingle Bundle Calculator",
    seoDescription: "Calculate shingle bundles needed from roofing squares and bundle coverage.",
    focusKeyword: "shingle bundle count calculator",
    formulaType: "tradeShingleBundleCount",
    description: "Convert squares to shingle bundle count with waste allowance.",
    formulaSummary: "Bundles = squares × bundles per square (typically 3) × waste factor.",
    realWorldExample: "25 squares × 3 bundles/sq + 10% waste → ~83 bundles.",
    inputs: [
      ["squares", "Roofing squares", 25, 1, 200, 0.5],
      ["bundlesPerSquare", "Bundles per square", 3, 2, 5, 1],
      ["wastePercent", "Waste (%)", 10, 0, 20, 1],
    ],
  },
  {
    slug: "gutter-downspout-calculator",
    title: "Gutter Downspout Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Gutter Capacity & Downspout Count Calculator",
    seoDescription:
      "Size gutters and count downspouts from roof area and rainfall intensity.",
    focusKeyword: "gutter downspout calculator",
    formulaType: "tradeGutterCapacity",
    description: "Estimate gutter flow capacity and recommended downspout count.",
    formulaSummary: "GPM demand = roof sq ft × rainfall in/hr × 0.0104; downspouts = demand ÷ capacity.",
    realWorldExample: "2,000 sq ft roof at 1 in/hr rainfall → ~21 GPM; 2–3 downspouts typical.",
    inputs: [
      ["roofAreaSqFt", "Roof area (sq ft)", 2000, 200, 20000, 50],
      ["rainfallInPerHr", "Rainfall intensity (in/hr)", 1, 0.5, 3, 0.1],
      ["downspoutGpm", "Downspout capacity (GPM)", 8, 4, 15, 1],
    ],
  },
  {
    slug: "vinyl-siding-cost-calculator",
    title: "Vinyl Siding Cost Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Vinyl Siding Square Footage & Cost Calculator",
    seoDescription:
      "Calculate siding squares from wall area minus openings with waste and cost.",
    focusKeyword: "vinyl siding cost calculator",
    formulaType: "tradeSidingSquareFootage",
    description: "Net siding area with waste and material/labor cost estimate.",
    formulaSummary: "Net sq ft = wall area − openings; squares = net × (1 + waste%) ÷ 100.",
    realWorldExample: "1,800 sq ft walls − 200 openings, 10% waste, $3/sq ft → ~$5,940 materials.",
    inputs: [
      ["wallAreaSqFt", "Wall area (sq ft)", 1800, 200, 20000, 50],
      ["openingsSqFt", "Openings (sq ft)", 200, 0, 2000, 25],
      ["wastePercent", "Waste (%)", 10, 5, 20, 1],
      ["costPerSqFt", "Material cost ($/sq ft)", 3, 1, 15, 0.25],
    ],
  },
  {
    slug: "fence-materials-calculator",
    title: "Fence Materials Estimator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Fence Material Calculator — Posts, Boards & Fasteners",
    seoDescription:
      "Estimate fence posts, boards, and pickets from run length, spacing, and height.",
    focusKeyword: "fence materials calculator",
    formulaType: "tradeFenceMaterials",
    description: "Count posts, rails, and pickets for a fence run.",
    formulaSummary: "Posts = ceil(length ÷ spacing) + 1; pickets = length ÷ picket width.",
    realWorldExample: "100 ft fence, 8 ft post spacing, 6 ft height → 14 posts + ~180 pickets.",
    inputs: [
      ["lengthFt", "Fence length (ft)", 100, 10, 1000, 5],
      ["postSpacingFt", "Post spacing (ft)", 8, 4, 12, 1],
      ["picketWidthIn", "Picket width (in)", 5.5, 3, 8, 0.5],
      ["fenceHeightFt", "Fence height (ft)", 6, 3, 8, 0.5],
    ],
  },
  {
    slug: "roof-pitch-angle-calculator",
    title: "Roof Pitch Angle Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Roof Pitch Calculator — Rise, Run, Angle & Multiplier",
    seoDescription: "Convert roof rise and run to pitch ratio, angle, and area multiplier.",
    focusKeyword: "roof pitch calculator rise run",
    formulaType: "tradeRoofPitchAngle",
    description: "Compute pitch, angle degrees, and slope multiplier from rise and run.",
    formulaSummary: "Pitch = rise:run; angle = atan(rise/run); multiplier = √(run² + rise²) ÷ run.",
    realWorldExample: "6 in rise per 12 in run → 6/12 pitch, ~26.6°, multiplier ~1.118.",
    inputs: [
      ["riseIn", "Rise (in)", 6, 1, 24, 0.5],
      ["runIn", "Run (in)", 12, 6, 24, 1],
    ],
  },
  {
    slug: "deck-joist-span-calculator",
    title: "Deck Joist Span Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Deck Joist Span Calculator",
    seoDescription:
      "Estimate max deck joist span from lumber depth, spacing, and design load.",
    focusKeyword: "deck joist span calculator",
    formulaType: "tradeDeckJoistSpan",
    description: "Rule-of-thumb max joist span from lumber size and spacing.",
    formulaSummary: "Span limits from simplified span tables by joist depth and spacing.",
    realWorldExample: "2×10 joists at 16 in OC, 40 PSF load → ~15 ft max span (verify locally).",
    inputs: [
      ["joistDepthIn", "Joist depth (in, e.g. 10 for 2×10)", 10, 6, 14, 1],
      ["spacingIn", "Joist spacing (in OC)", 16, 12, 24, 2],
      ["loadPsf", "Design load (PSF)", 40, 30, 60, 5],
    ],
  },
  {
    slug: "roof-shingle-weight-calculator",
    title: "Roof Shingle Weight Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Asphalt Shingle Weight Calculator",
    seoDescription: "Calculate total roof load from roofing squares and shingle weight per square.",
    focusKeyword: "roof shingle weight calculator",
    formulaType: "tradeShingleWeightLoad",
    description: "Total shingle weight on structure from squares and lbs/square.",
    formulaSummary: "Total weight = squares × lbs per square.",
    realWorldExample: "25 squares × 230 lbs/sq → 5,750 lbs on roof structure.",
    inputs: [
      ["squares", "Roofing squares", 25, 1, 200, 0.5],
      ["lbsPerSquare", "Shingle weight (lbs/square)", 230, 150, 400, 10],
    ],
  },
  {
    slug: "exterior-paint-coverage-calculator",
    title: "Exterior Paint Coverage Calculator",
    category: ROOFING_TRADES_CATEGORY,
    seoH1: "Exterior Paint Calculator — Gallons by Square Feet",
    seoDescription:
      "Estimate exterior paint gallons from surface area, coats, coverage, and waste.",
    focusKeyword: "exterior paint calculator square feet",
    formulaType: "tradeExteriorPaintCoverage",
    description: "Gallons needed for exterior paint from surface area and coverage rate.",
    formulaSummary: "Gallons = (sq ft × coats × (1 + waste%)) ÷ coverage per gallon.",
    realWorldExample: "2,000 sq ft, 2 coats, 350 sq ft/gal, 10% waste → ~12.6 gallons.",
    inputs: [
      ["surfaceSqFt", "Surface area (sq ft)", 2000, 100, 20000, 50],
      ["coats", "Coats", 2, 1, 4, 1],
      ["coveragePerGal", "Coverage (sq ft/gal)", 350, 200, 500, 10],
      ["wastePercent", "Waste (%)", 10, 0, 25, 1],
    ],
  },

  // ——— Construction & Bidding (11) ———
  {
    slug: "job-bid-profit-calculator",
    title: "Job Bid Profit Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Construction Job Bid Profit Calculator — Markup & Margin",
    seoDescription:
      "Build a job bid from materials, labor, overhead, and markup. See cost, profit, and margin %.",
    focusKeyword: "construction job bid profit calculator",
    formulaType: "tradeJobBidProfit",
    description:
      "Calculate bid price, net profit, and margin from materials, labor hours, overhead, and markup.",
    formulaSummary:
      "Direct cost = materials + labor + overhead; bid = direct cost × (1 + markup%).",
    realWorldExample:
      "$2,400 materials + 16 hrs × $55/hr + $300 overhead, 20% markup → $4,060 bid, ~16.7% margin.",
    inputs: [
      ["materials", "Materials ($)", 2400, 0, 500000, 50],
      ["laborHours", "Labor hours", 16, 0, 500, 0.5],
      ["laborRate", "Labor rate ($/hr)", 55, 15, 200, 1],
      ["overhead", "Overhead ($)", 300, 0, 50000, 25],
      ["markupPercent", "Markup on cost (%)", 20, 0, 100, 1],
    ],
  },
  {
    slug: "change-order-impact-calculator",
    title: "Change Order Impact Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Construction Change Order Impact Calculator",
    seoDescription:
      "See revised job total, margin, and profit delta after a change order.",
    focusKeyword: "change order impact calculator",
    formulaType: "tradeChangeOrderImpact",
    description: "Compare original vs revised bid margin after scope/cost changes.",
    formulaSummary:
      "New margin = (revised price − revised cost) ÷ revised price; delta = new profit − old profit.",
    realWorldExample: "$50k job + $8k added cost at $12k added price → margin compression visible.",
    inputs: [
      ["originalPrice", "Original bid ($)", 50000, 1000, 5000000, 500],
      ["originalCost", "Original cost ($)", 40000, 500, 5000000, 500],
      ["addedCost", "Added cost ($)", 8000, 0, 500000, 100],
      ["addedPrice", "Added price ($)", 12000, 0, 500000, 100],
    ],
  },
  {
    slug: "concrete-volume-calculator",
    title: "Concrete Volume Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Concrete Volume Calculator — Cubic Yards & Bags",
    seoDescription:
      "Calculate concrete cubic yards and bag count from L×W×D with labor cost.",
    focusKeyword: "concrete volume calculator cubic yards",
    formulaType: "tradeConcreteVolume",
    description: "Volume in cu yd and 80 lb bags from slab dimensions.",
    formulaSummary: "Cu ft = L × W × (D in ÷ 12); cu yd = cu ft ÷ 27; bags = cu ft ÷ bag yield.",
    realWorldExample: "10×12 ft slab, 4 in thick → ~1.48 cu yd, ~22 80 lb bags.",
    inputs: [
      ["lengthFt", "Length (ft)", 10, 1, 200, 1],
      ["widthFt", "Width (ft)", 12, 1, 200, 1],
      ["depthIn", "Depth (in)", 4, 2, 24, 0.5],
      ["bagYieldCuFt", "Bag yield (cu ft)", 0.6, 0.4, 1, 0.05],
      ["bagCost", "Cost per bag ($)", 5, 2, 20, 0.5],
      ["laborCost", "Labor ($)", 200, 0, 10000, 25],
    ],
  },
  {
    slug: "remodel-cost-ballpark-calculator",
    title: "Remodel Room Cost Ballpark Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Room Remodel Cost Ballpark Calculator",
    seoDescription:
      "Ballpark remodel cost range from square footage and cost per sq ft tier.",
    focusKeyword: "remodel room cost ballpark calculator",
    formulaType: "tradeRemodelCostBallpark",
    description: "Low/high remodel estimate from room size and $/sq ft range.",
    formulaSummary: "Cost range = sq ft × low $/sq ft to sq ft × high $/sq ft.",
    realWorldExample: "200 sq ft bathroom at $150–$250/sq ft → $30k–$50k ballpark.",
    inputs: [
      ["sqFt", "Room sq ft", 200, 50, 5000, 10],
      ["costPerSqFtLow", "Low $/sq ft", 150, 50, 500, 10],
      ["costPerSqFtHigh", "High $/sq ft", 250, 75, 800, 10],
    ],
  },
  {
    slug: "subcontractor-bid-compare-calculator",
    title: "Subcontractor Bid Compare Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Subcontractor Bid Comparison Calculator",
    seoDescription: "Compare up to three subcontractor bids and highlight the spread.",
    focusKeyword: "subcontractor bid compare calculator",
    formulaType: "tradeSubcontractorBidCompare",
    description: "Side-by-side sub bid compare with low bid and spread.",
    formulaSummary: "Low bid = min(bids); spread = high − low; avg for context.",
    realWorldExample: "Bids $18k, $21k, $19.5k → low $18k, spread $3k.",
    inputs: [
      ["bid1", "Bid 1 ($)", 18000, 0, 5000000, 500],
      ["bid2", "Bid 2 ($)", 21000, 0, 5000000, 500],
      ["bid3", "Bid 3 ($)", 19500, 0, 5000000, 500],
    ],
  },
  {
    slug: "drywall-sheet-mud-calculator",
    title: "Drywall Sheet & Mud Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Drywall Calculator — Sheets, Mud & Tape",
    seoDescription:
      "Estimate drywall sheets, joint compound, and tape from room dimensions.",
    focusKeyword: "drywall calculator sheets mud",
    formulaType: "tradeDrywallSheetMud",
    description: "Sheets and mud from wall/ceiling surface area with waste.",
    formulaSummary: "Sheets = wall+ceiling sq ft ÷ 32 (4×8) × waste; mud ≈ sq ft × factor.",
    realWorldExample: "12×14×8 room → ~13 sheets + ~4 gal mud (rough estimate).",
    inputs: [
      ["roomLengthFt", "Room length (ft)", 12, 4, 50, 1],
      ["roomWidthFt", "Room width (ft)", 14, 4, 50, 1],
      ["roomHeightFt", "Ceiling height (ft)", 8, 7, 12, 0.5],
      ["wastePercent", "Waste (%)", 10, 0, 20, 1],
    ],
  },
  {
    slug: "interior-paint-room-calculator",
    title: "Interior Paint Room Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Interior Paint Calculator — Room Gallons",
    seoDescription: "Gallons of interior paint from room dimensions, coats, and coverage.",
    focusKeyword: "paint calculator room square feet",
    formulaType: "tradeInteriorPaintRoom",
    description: "Interior paint gallons for walls and ceiling.",
    formulaSummary: "Paintable sq ft = walls + ceiling − openings; gallons = sq ft × coats ÷ coverage.",
    realWorldExample: "12×14×8 room, 2 coats, 400 sq ft/gal → ~3–4 gallons walls+ceiling.",
    inputs: [
      ["roomLengthFt", "Room length (ft)", 12, 4, 50, 1],
      ["roomWidthFt", "Room width (ft)", 14, 4, 50, 1],
      ["roomHeightFt", "Ceiling height (ft)", 8, 7, 12, 0.5],
      ["openingsSqFt", "Openings (sq ft)", 60, 0, 500, 5],
      ["coats", "Coats", 2, 1, 4, 1],
      ["coveragePerGal", "Coverage (sq ft/gal)", 400, 250, 500, 10],
    ],
  },
  {
    slug: "crew-day-rate-vs-piece-rate-calculator",
    title: "Crew Day-Rate vs Piece-Rate Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Crew Day Rate vs Piece Rate Calculator",
    seoDescription:
      "Compare crew day-rate cost vs piece-rate cost for effective $/hr and job total.",
    focusKeyword: "crew day rate vs piece rate calculator",
    formulaType: "tradeCrewDayRateVsPieceRate",
    description: "Effective hourly and job cost for day-rate vs piece-rate crews.",
    formulaSummary: "Day cost = crew × hours × rate; piece cost = quantity × piece rate.",
    realWorldExample: "3 crew × 8 hrs × $45 vs 120 units × $12 → compare effective $/hr.",
    inputs: [
      ["crewSize", "Crew size", 3, 1, 20, 1],
      ["hours", "Hours on job", 8, 1, 24, 0.5],
      ["dayRatePerPerson", "Day rate per person ($/hr)", 45, 20, 150, 5],
      ["pieceQuantity", "Piece quantity", 120, 1, 10000, 10],
      ["pieceRate", "Piece rate ($/unit)", 12, 1, 500, 1],
    ],
  },
  {
    slug: "permit-overhead-recovery-calculator",
    title: "Permit & Overhead Recovery Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Construction Overhead Recovery Calculator",
    seoDescription:
      "Allocate monthly overhead and permit fees across job days for bid add-on.",
    focusKeyword: "construction overhead recovery calculator",
    formulaType: "tradePermitOverheadRecovery",
    description: "Overhead recovery add-on per job from monthly overhead and job duration.",
    formulaSummary: "Daily overhead = monthly overhead ÷ working days; job add-on = daily × job days + permits.",
    realWorldExample: "$8k/month overhead, 20 working days, 10-day job + $400 permit → ~$4,400 add-on.",
    inputs: [
      ["monthlyOverhead", "Monthly overhead ($)", 8000, 500, 100000, 250],
      ["workingDaysPerMonth", "Working days/month", 20, 10, 26, 1],
      ["jobDays", "Job duration (days)", 10, 1, 180, 1],
      ["permitFees", "Permit fees ($)", 400, 0, 10000, 50],
    ],
  },
  {
    slug: "equipment-rental-vs-buy-calculator",
    title: "Equipment Rental vs Buy Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Equipment Rental vs Buy Calculator",
    seoDescription:
      "Compare rental cost vs purchase with maintenance over years to find break-even.",
    focusKeyword: "equipment rental vs buy calculator",
    formulaType: "tradeEquipmentRentalVsBuy",
    description: "Break-even days/years between renting and buying equipment.",
    formulaSummary: "Rent total = $/day × days; buy total = purchase + maint × years.",
    realWorldExample: "$350/day rental vs $45k purchase + $2k/yr maint → break-even ~130 rental days.",
    inputs: [
      ["rentalPerDay", "Rental ($/day)", 350, 50, 2000, 25],
      ["rentalDays", "Days needed", 30, 1, 365, 1],
      ["purchaseCost", "Purchase cost ($)", 45000, 1000, 500000, 500],
      ["annualMaint", "Annual maintenance ($)", 2000, 0, 20000, 100],
      ["yearsOwned", "Years owned (if buy)", 5, 1, 20, 1],
    ],
  },
  {
    slug: "job-contingency-calculator",
    title: "Job Contingency Calculator",
    category: CONSTRUCTION_TRADES_CATEGORY,
    seoH1: "Construction Contingency Calculator",
    seoDescription:
      "Recommended contingency dollars and percent from job value and risk tier.",
    focusKeyword: "construction contingency calculator",
    formulaType: "tradeJobContingency",
    description: "Contingency $ and % from job value and risk tier.",
    formulaSummary: "Contingency = job value × risk tier %.",
    realWorldExample: "$80k job at 8% medium risk → $6,400 contingency reserve.",
    inputs: [
      ["jobValue", "Job value ($)", 80000, 1000, 5000000, 500],
      ["riskPercent", "Risk contingency (%)", 8, 3, 20, 1],
    ],
  },

  // ——— Landscaping & Hardscape (6) ———
  {
    slug: "mulch-cubic-yards-calculator",
    title: "Mulch Cubic Yards Calculator",
    category: LANDSCAPING_TRADES_CATEGORY,
    seoH1: "Mulch Calculator — Cubic Yards & Bags",
    seoDescription: "Calculate mulch cubic yards from bed area and depth in inches.",
    focusKeyword: "mulch calculator cubic yards",
    formulaType: "tradeMulchCubicYards",
    description: "Mulch volume in cubic yards and bag count from area and depth.",
    formulaSummary: "Cu yd = (area sq ft × depth in ÷ 12) ÷ 27.",
    realWorldExample: "500 sq ft beds at 3 in depth → ~3.7 cubic yards.",
    inputs: [
      ["areaSqFt", "Bed area (sq ft)", 500, 50, 10000, 25],
      ["depthIn", "Depth (in)", 3, 1, 12, 0.5],
      ["costPerCuYd", "Cost per cu yd ($)", 45, 10, 200, 5],
    ],
  },
  {
    slug: "sod-square-footage-calculator",
    title: "Sod Square Footage Calculator",
    category: LANDSCAPING_TRADES_CATEGORY,
    seoH1: "Sod Calculator — Square Feet & Cost",
    seoDescription: "Sod sq ft with waste allowance and material cost estimate.",
    focusKeyword: "sod calculator square feet",
    formulaType: "tradeSodSquareFootage",
    description: "Sod order sq ft including waste and cost.",
    formulaSummary: "Order sq ft = lawn sq ft × (1 + waste%); pallets ≈ sq ft ÷ 450.",
    realWorldExample: "1,200 sq ft lawn + 5% waste at $0.45/sq ft → ~$567 sod cost.",
    inputs: [
      ["lawnSqFt", "Lawn sq ft", 1200, 100, 20000, 50],
      ["wastePercent", "Waste (%)", 5, 0, 15, 1],
      ["costPerSqFt", "Sod cost ($/sq ft)", 0.45, 0.2, 2, 0.05],
    ],
  },
  {
    slug: "gravel-driveway-calculator",
    title: "Gravel Driveway Calculator",
    category: LANDSCAPING_TRADES_CATEGORY,
    seoH1: "Gravel Driveway Calculator — Tons & Cost",
    seoDescription: "Gravel tons and cost from driveway length, width, and depth.",
    focusKeyword: "gravel driveway calculator tons",
    formulaType: "tradeGravelDrivewayDepth",
    description: "Gravel volume converted to tons with delivery cost estimate.",
    formulaSummary: "Cu yd = L × W × (depth in ÷ 12) ÷ 27; tons ≈ cu yd × 1.4.",
    realWorldExample: "40×12 ft driveway, 4 in gravel → ~2.4 cu yd, ~3.4 tons.",
    inputs: [
      ["lengthFt", "Length (ft)", 40, 5, 500, 5],
      ["widthFt", "Width (ft)", 12, 4, 50, 1],
      ["depthIn", "Depth (in)", 4, 2, 12, 0.5],
      ["costPerTon", "Cost per ton ($)", 55, 20, 150, 5],
    ],
  },
  {
    slug: "irrigation-zone-gpm-calculator",
    title: "Irrigation Zone GPM Calculator",
    category: LANDSCAPING_TRADES_CATEGORY,
    seoH1: "Sprinkler Zone GPM Calculator",
    seoDescription: "Zone GPM from sprinkler head count and flow per head.",
    focusKeyword: "sprinkler zone gpm calculator",
    formulaType: "tradeIrrigationZoneGpm",
    description: "Total zone GPM demand for irrigation design check.",
    formulaSummary: "Zone GPM = heads × GPM per head.",
    realWorldExample: "8 rotors at 2.5 GPM → 20 GPM zone (verify supply capacity).",
    inputs: [
      ["headCount", "Sprinkler heads", 8, 1, 50, 1],
      ["gpmPerHead", "GPM per head", 2.5, 0.5, 10, 0.1],
      ["supplyGpm", "Available supply GPM", 15, 5, 50, 1],
    ],
  },
  {
    slug: "retaining-wall-block-calculator",
    title: "Retaining Wall Block Calculator",
    category: LANDSCAPING_TRADES_CATEGORY,
    seoH1: "Retaining Wall Block Calculator",
    seoDescription: "Block count and gravel backfill from wall length and height.",
    focusKeyword: "retaining wall block calculator",
    formulaType: "tradeRetainingWallBlocks",
    description: "Blocks needed for retaining wall face area.",
    formulaSummary: "Blocks = (length × height) ÷ block face sq ft × waste factor.",
    realWorldExample: "20 ft × 3 ft wall, 0.5 sq ft blocks + 10% waste → ~132 blocks.",
    inputs: [
      ["wallLengthFt", "Wall length (ft)", 20, 2, 200, 1],
      ["wallHeightFt", "Wall height (ft)", 3, 1, 10, 0.5],
      ["blockFaceSqFt", "Block face (sq ft)", 0.5, 0.1, 2, 0.05],
      ["wastePercent", "Waste (%)", 10, 0, 20, 1],
    ],
  },
  {
    slug: "paver-patio-material-calculator",
    title: "Paver Patio Material Calculator",
    category: LANDSCAPING_TRADES_CATEGORY,
    seoH1: "Paver Patio Calculator — Pavers & Base Gravel",
    seoDescription:
      "Paver count and base gravel from patio area, paver size, and waste.",
    focusKeyword: "paver patio calculator",
    formulaType: "tradePaverPatioMaterial",
    description: "Pavers and base gravel volume for patio install.",
    formulaSummary: "Pavers = patio sq ft ÷ paver sq ft × waste; base cu yd from depth.",
    realWorldExample: "200 sq ft patio, 12×12 pavers, 4 in base → ~200 pavers + ~2.5 cu yd gravel.",
    inputs: [
      ["patioSqFt", "Patio sq ft", 200, 50, 5000, 25],
      ["paverSqFt", "Paver size (sq ft each)", 1, 0.25, 4, 0.05],
      ["wastePercent", "Waste (%)", 10, 0, 20, 1],
      ["baseDepthIn", "Base gravel depth (in)", 4, 2, 8, 0.5],
    ],
  },

  // ——— Masonry & Concrete (4) ———
  {
    slug: "brick-wall-mortar-calculator",
    title: "Brick Wall Mortar Calculator",
    category: MASONRY_TRADES_CATEGORY,
    seoH1: "Brick Wall Mortar Calculator",
    seoDescription: "Bricks and mortar bags from wall area and brick size.",
    focusKeyword: "brick wall mortar calculator",
    formulaType: "tradeBrickWallMortar",
    description: "Brick count and mortar bags for a brick wall.",
    formulaSummary: "Bricks = wall sq ft × bricks/sq ft; mortar bags ≈ sq ft × factor.",
    realWorldExample: "80 sq ft wall, 6.75 bricks/sq ft → ~540 bricks + ~8 mortar bags.",
    inputs: [
      ["wallSqFt", "Wall area (sq ft)", 80, 10, 2000, 10],
      ["bricksPerSqFt", "Bricks per sq ft", 6.75, 4, 10, 0.25],
      ["mortarBagsPerSqFt", "Mortar bags per sq ft", 0.1, 0.05, 0.3, 0.01],
    ],
  },
  {
    slug: "cmu-block-count-calculator",
    title: "CMU Block Count Calculator",
    category: MASONRY_TRADES_CATEGORY,
    seoH1: "Concrete Block Wall Calculator",
    seoDescription: "CMU block count from wall square footage and block face size.",
    focusKeyword: "cmu block count calculator",
    formulaType: "tradeCmuBlockCount",
    description: "Count concrete masonry units for a wall.",
    formulaSummary: "Blocks = wall sq ft ÷ block face sq ft × (1 + waste%).",
    realWorldExample: "120 sq ft wall, 1.125 sq ft blocks → ~117 blocks + waste.",
    inputs: [
      ["wallSqFt", "Wall area (sq ft)", 120, 10, 5000, 10],
      ["blockFaceSqFt", "Block face (sq ft)", 1.125, 0.5, 2, 0.05],
      ["wastePercent", "Waste (%)", 5, 0, 15, 1],
    ],
  },
  {
    slug: "rebar-spacing-weight-calculator",
    title: "Rebar Spacing & Weight Calculator",
    category: MASONRY_TRADES_CATEGORY,
    seoH1: "Rebar Weight Calculator by Length & Spacing",
    seoDescription: "Rebar stick count and total weight from run length and spacing.",
    focusKeyword: "rebar spacing weight calculator",
    formulaType: "tradeRebarSpacingWeight",
    description: "Rebar pieces and weight for a slab or footing run.",
    formulaSummary: "Pieces = length ÷ spacing + 1; weight = pieces × length × lb/ft.",
    realWorldExample: "40 ft run, 12 in spacing, #4 bar → 41 sticks, ~164 ft, ~110 lbs.",
    inputs: [
      ["runLengthFt", "Run length (ft)", 40, 5, 500, 5],
      ["spacingIn", "Spacing (in OC)", 12, 6, 24, 2],
      ["barWeightLbPerFt", "Bar weight (lb/ft)", 0.668, 0.2, 2, 0.01],
    ],
  },
  {
    slug: "post-hole-concrete-calculator",
    title: "Post Hole Concrete Calculator",
    category: MASONRY_TRADES_CATEGORY,
    seoH1: "Post Hole Concrete Bag Calculator",
    seoDescription: "Concrete bags for fence/deck posts from hole diameter and depth.",
    focusKeyword: "post hole concrete calculator",
    formulaType: "tradePostHoleConcrete",
    description: "Bags of concrete for cylindrical post holes.",
    formulaSummary: "Cu ft per hole = π × (d/2)² × depth; bags = total cu ft ÷ bag yield.",
    realWorldExample: "6 holes, 10 in diameter, 36 in deep → ~4.5 cu ft, ~8 bags.",
    inputs: [
      ["holeCount", "Post holes", 6, 1, 100, 1],
      ["diameterIn", "Hole diameter (in)", 10, 6, 24, 1],
      ["depthIn", "Hole depth (in)", 36, 12, 48, 2],
      ["bagYieldCuFt", "Bag yield (cu ft)", 0.6, 0.4, 1, 0.05],
      ["bagCost", "Cost per bag ($)", 5, 2, 20, 0.5],
    ],
  },
];
